# Generated by Django 3.2 on 2021-04-25 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_worth', models.FloatField()),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(max_length=40)),
                ('iso_code', models.TextField(max_length=40)),
                ('points', models.IntegerField()),
                ('rank', models.IntegerField(default=888888)),
            ],
        ),
    ]
